# Generated by cucumber-sinatra. (2015-02-27 16:55:24 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', 'lib/app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Oodls

class OodlsWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  OodlsWorld.new
end
